---
- name: backup origin yum repos
  shell:
    cmd: "mkdir bak; mv *.repo bak"
    chdir: /etc/yum.repos.d
    creates: /etc/yum.repos.d/bak
  tags: upgrade_repo

- name: add os repo and epel repo
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - Centos-7.repo
    - epel-7.repo
  tags: upgrade_repo

- name: basic lib install
  # yum 模块执行较慢，这个直接用 shell 模块
  shell: "yum -y install {{ item }}"
  loop: "{{ pkgs.lib }}"
  tags: install_pkgs

- name: basic tools install
  shell: "yum -y install {{ item }}"
  loop: "{{ pkgs.tools }}"
  tags: install_pkgs